require("user.options")
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.lsp.null-ls"
require "user.closetag"
require "user.nvim-tree"
require "user.lspsaga"
vim.cmd "colorscheme tokyonight"
vim.g.airline_theme = "base16_dracula"
